### ISSUE TITLE
broken luquidity button

### ISSUE THREAD

**Issue by kylemonper** [balancer-labs/pool-management#98]
Sorry if this is the wrong forum for this, but wasn't sure how else to reach out.
Im using google chrome on windows 10 at the following link:
https://noproxy.pools.balancer.exchange/#/pool/0x0e511Aa1a137AaD267dfe3a6bFCa0b856C1a3682

after unlocking all coins, setting a proper equal levels amount of tokens for each, the `add liquidity` button is not working. My browser recognizes it as clickable (the pointing hand appears when hovering) but nothing happens when pressed.

again, sorry if this is the wrong place to submit an issue, feel free to link the appropriate method and resolve this

**Comment by mikemcdonald** [comment]
This should be resolved. Feel free to re-open and/or reach out on Discord if you see any issue
